base_url = "https://zola-after-dark.netlify.com"
compile_sass = true
title = "after-dark theme"
description = "After Dark Demo"

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

highlight_code = true
highlight_theme = "base16-ocean-dark"


[extra]
author = "Vincent"
after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
]
after_dark_title = "My blog"

katex_enable = true
katex_auto_render = true
